"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'tr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

// Translation data will be imported here
const translations = {
  en: {
    // Header
    'system.active': 'SYSTEM ACTIVE',
    'system.title': 'Uninterrupted Communication and Rapid Damage Detection in Disasters',
    'system.subtitle': 'Next-Generation Disaster Management with Helium, IoT and Blockchain Technologies',
    'latest.earthquake.data': 'Latest Earthquake Data',
    'active.hotspots': 'Active Hotspots',
    'connected.sensors': 'Connected Sensors',
    'todays.alerts': "Today's Alerts",
    'response.time': 'Response Time',

    // Modal
    'welcome.modal.platform.type': 'Disaster Management Platform',
    'welcome.modal.title': 'Welcome to RUPTURA',
    'welcome.modal.demo.purpose.title': 'Demonstration Purpose',
    'welcome.modal.demo.purpose.desc': 'This platform showcases the RUPTURA system\'s capabilities through simulated data and scenarios. All data is for demonstration only.',
    'welcome.modal.platform.aim.title': 'Platform Aim',
    'welcome.modal.platform.aim.desc': 'To provide an interactive experience of how RUPTURA can revolutionize disaster communication and damage assessment.',
    'welcome.modal.content.info.title': 'Content Information',
    'welcome.modal.content.info.item1': 'Simulated sensor data and damage reports.',
    'welcome.modal.content.info.item2': 'Real-time visualizations and animations.',
    'welcome.modal.content.info.item3': 'Proof of concept for technological features.',
    'welcome.modal.usage.terms.title': 'Usage Terms',
    'welcome.modal.usage.terms.desc': 'This platform is for informational and educational purposes only. Not for use in real emergencies.',
    'welcome.modal.button.text': 'Acknowledge & Proceed',
    'welcome.modal.first.visit.message': 'This message is shown only on your first visit.',
    // Old Modal Keys (can be reviewed or removed later if not used elsewhere)
    'important.notice': 'Important Notice',
    'demo.simulation.platform': 'Demo and Simulation Platform',
    'demo.simulation.desc': 'All data on this site is for simulation and demo purposes. It is not real earthquake data, damage information or emergency data.',
    'platform.purpose': 'Platform Purpose',
    'platform.purpose.desc': 'It is an interactive demonstration platform designed to show the technological capabilities of the RUPTURA system and how it works.',
    'content.about': 'About Content',
    'content.item1': 'Dummy sensor data and damage simulations',
    'content.item2': 'Real-time animations and visualizations',
    'content.item3': 'Technology demonstration and proof of concept',
    'usage.conditions': 'Terms of Use',
    'usage.conditions.desc': 'The platform is only for informational, educational and technology promotion purposes. It should not be used in real emergencies.',
    'understood.enter': 'Understood, Enter Platform',
    'first.visit.message': 'This message is only shown on your first visit', // Kept for potential other uses, new key is welcome.modal.first.visit.message

    // Crisis Section
    'current.situation': 'Current Situation: Communication Crisis During Disasters',
    'current.situation.desc': 'When traditional infrastructures collapse, life-saving information is lost',
    'communication.outage': 'Communication Outage',
    'potential.infrastructure.loss': 'Potential infrastructure loss observed in major disasters in Turkey',
    'gsm.outages': 'GSM and Landline Outages',
    'physical.damage.overload': 'Physical damage and overload',
    'delayed.damage.detection': 'Delayed Damage Detection',
    'manual.processes.risks': 'Manual processes and security risks',
    'coordination.deficiency': 'Coordination Deficiency',
    'inefficiency.aid.operations': 'Inefficiency in aid operations',

    // Solution
    'ruptura.solution': 'RUPTURA Solution: Decentralized Network',
    'ruptura.solution.desc': 'Revolutionary disaster management with IoT, Helium and Blockchain',
    'iot.sensors': 'IoT Sensors',
    'iot.sensors.desc': 'Real-time damage detection',
    'helium.network': 'Helium Network',
    'helium.network.desc': 'Decentralized communication',
    'blockchain': 'Blockchain',
    'blockchain.desc': 'Immutable data recording',
    'gis.aid': 'GIS & Aid',
    'gis.aid.desc': 'Automatic coordination',

    // Map Section
    'turkey.realtime.damage.map': 'Turkey Real-Time Damage Map',
    'turkey.map.desc': 'Instant damage detection and visualization with RUPTURA system',
    'turkey.map.detail': 'You can view detailed damage information at district and street level by zooming in on Istanbul',
    'map.controls': 'Map Controls',
    'zoom.in': 'Zoom In',
    'zoom.out': 'Zoom Out',
    'istanbul.detail': 'Istanbul Detail',
    'all.damages': 'All Damages',
    'collapsed.buildings': 'Collapsed Buildings',
    'severely.damaged': 'Severely Damaged',
    'infrastructure.damages': 'Infrastructure Damages',
    'live.data': 'Live Data',
    'map.loading': 'Map loading...',
    'detailed.map.exploration': 'Detailed Map Exploration',
    'zoom.istanbul.desc': 'Zoom in to Istanbul and see real street-level damage simulations! Detailed information is available for each building.',
    'go.to.istanbul': 'Go to Istanbul',
    'damage.levels': 'Damage Levels',
    'high.damage': 'High Damage (>15%)',
    'medium.damage': 'Medium Damage (8-15%)',
    'low.damage': 'Low Damage (3-8%)',
    'minimal.damage': 'Minimal Damage (<3%)',
    'tip': 'Tip',
    'zoom.istanbul.tip': 'Zoom to Istanbul',
    'street.level.details': 'Street level details',
    'info.each.building': 'Information for each building',
    'detailed.map.experience': 'Detailed Map Experience',
    'zoom.istanbul.experience': 'By zooming in to Istanbul city, discover real street names, building numbers and detailed damage simulations. You can view floor count, resident count and damage status information for each building.',
    'building.details': '150+ Building Details',
    'district.coverage': '10 District Coverage',
    'real.addresses': 'Real Addresses',
    'explore.now': 'Explore Now',

    // Emergency Teams
    'emergency.teams.live.tracking': 'Emergency Teams Live Tracking',
    'emergency.teams.desc': 'Real-time locations of Police, Fire Department, AFAD, AKUT and Health teams',
    'emergency.teams.detail': 'Real-time response status and mission information of all search and rescue teams',
    'under.research': 'UNDER RESEARCH',
    'feature.under.research': 'Feature Under Research',
    'emergency.teams.system': 'Emergency Teams Live Tracking System',
    'realtime.location': 'Real-time Location',
    'realtime.location.desc': 'Live tracking of all emergency teams',
    'team.coordination': 'Team Coordination',
    'team.coordination.desc': 'Police, Fire Department, AFAD, AKUT integration',
    'mission.management': 'Mission Management',
    'mission.management.desc': 'Automatic task assignment and tracking',
    'ruptura.integration': 'RUPTURA Integration',
    'ruptura.integration.desc': 'Automatic routing with sensor data',
    'research.phase.desc': 'This feature is currently in the research phase, and technology and feasibility studies are ongoing.', // Value for feature.under.research.desc
    'feature.under.research.desc': 'This feature is currently in the research phase, and technology and feasibility studies are ongoing.',
    'research.phase': 'Research Phase',
    'technology.review': 'Technology Review',
    'implementation.planning': 'Implementation Planning',
    'under.research.status': 'Under Research',
    'feature.under.research.title': 'Feature Under Research', // Value from 'feature.under.research'
    'emergency.teams.live.tracking.system': 'Emergency Teams Live Tracking System', // Value from 'emergency.teams.system'
    'police.coordination': 'Police Coordination',
    'police.coordination.desc': 'Real-time locations and mission status of police teams',
    'firedept.afad': 'Fire Department & AFAD',
    'firedept.afad.desc': 'Live tracking of fire, rescue and coordination teams',
    'health.akut': 'Health & AKUT',
    'health.akut.desc': 'Automatic routing of ambulance and search rescue teams',

    // Statistics
    'total.collapsed.buildings': 'Total Collapsed Buildings',
    'turkey.wide': 'Turkey-wide',
    'severely.damaged.buildings': 'Severely Damaged',
    'urgent.intervention.required': 'Urgent Intervention Required',
    'affected.cities': 'Affected Cities',
    'active.monitoring': 'Active Monitoring',
    'active.sensors': 'Active Sensors',
    'data.collection': 'Data Collection',

    // Map Data
    'population': 'Population',
    'total.buildings': 'Total Buildings',
    'damaged.buildings': 'Damaged Buildings',
    'damage.rate': 'Damage Rate',
    'show.details': 'Show Details',
    'address': 'Address',
    'district': 'District',
    'status': 'Status',
    'floor.count': 'Floor Count',
    'residents': 'Residents',
    'time': 'Time',
    'building.damage': 'Building Damage',
    'collapsed': 'Collapsed',
    'severe': 'Severely Damaged',
    'moderate': 'Moderately Damaged',
    'light': 'Lightly Damaged',
    'intact': 'Intact',

    // City Details
    'detailed.damage.report': 'Detailed Damage Report',
    'building.statistics': 'Building Statistics',
    'recent.events': 'Recent Events',
    'damage.distribution': 'Damage Distribution',

    // Market Potential
    'market.potential.growth': 'Market Potential and Growth',
    'helium.hotspots': 'Active Helium Hotspots',
    'country.coverage': 'Country Coverage',
    'cities.towns': 'Cities/Towns',

    // Technology Stack
    'technology.stack': 'Technology Stack',
    'smart.sensor.technologies': 'Smart Sensor Technologies',
    'accelerometers': 'Accelerometers (MEMS)',
    'vibration.detection': 'Shock and vibration',
    'omron.d7s': 'Omron D7S',
    'earthquake.intensity': 'Earthquake intensity detection',
    'strain.gauges': 'Strain Gauges',
    'structural.deformation': 'Structural deformation',
    'gps.sensors': 'GPS Sensors',
    'precise.location': 'Precise location tracking',
    'edge.computing.ai': 'Edge Computing and AI',
    'realtime.processing': 'Real-time Processing',
    'realtime.processing.desc': 'Local filtering of raw seismic data and generation of LoRaWAN compatible summary metrics',
    'machine.learning': 'Machine Learning',
    'machine.learning.desc': 'Advanced AI models for damage prediction algorithms and anomaly detection',

    // Live System Demo
    'ruptura.live.demo': 'RUPTURA Live System Demonstration',
    'ruptura.demo.desc': 'Smart Contract Activation and Instant Alert System Based on Omron Sensor Data',
    'ruptura.demo.detail': 'Real-time sensor data, smart contract triggers and animated alert visualizations',

    // System Components
    'system.components.demo': 'System Components - Live Demonstration',
    'system.components.desc': 'Real-time operation demonstration of all components of the RUPTURA system',
    'omron.sensor.network': 'Omron D7S Sensor Network Simulator',
    'omron.sensor.desc': 'Real-time data generation and damage analysis of Omron D7S sensors distributed throughout Istanbul',
    'helium.lorawan.monitor': 'Helium LoRaWAN Network Monitor',
    'helium.monitor.desc': 'Transmission of sensor data over the decentralized Helium network and network performance metrics',
    'smart.contract.processor': 'Smart Contract Processor',
    'smart.contract.desc': 'Processing sensor data on blockchain, damage analysis and automatic response triggers',

    // Blockchain Benefits
    'blockchain.trust.transparency': 'Trust and Transparency with Blockchain',
    'immutable.record': 'Immutable Record',
    'immutable.record.desc': 'Data cannot be changed later',
    'full.transparency': 'Full Transparency',
    'full.transparency.desc': 'All transactions are visible',
    'reliability': 'Reliability',
    'reliability.desc': 'System closed to manipulation',
    'automatic.aid.smart.contracts': 'Automatic Aid with Smart Contracts',
    'automatic.aid.desc': 'Automatically triggering emergency aid processes according to predefined rules',
    'example.scenario': 'Example Scenario:',
    'jma.scenario': '"JMA 5+ intensity shaking + collapse flag → Automatic search-rescue team notification"',

    // SWOT Analysis
    'turkey.market.swot': 'Turkey Market: SWOT Analysis',
    'swot.strengths.title': 'Strengths',
    'swot.weaknesses.title': 'Weaknesses',
    'swot.opportunities.title': 'Opportunities',
    'swot.threats.title': 'Threats',
    'swot.strengths.item1': 'Decentralized, resilient communication',
    'swot.strengths.item2': 'Real-time damage detection',
    'swot.strengths.item3': 'Transparent data management',
    'swot.strengths.item4': 'Automatic coordination',
    'swot.weaknesses.item1': 'LoRaWAN data limitations',
    'swot.weaknesses.item2': 'Initial setup cost',
    'swot.weaknesses.item3': 'Network density dependency',
    'swot.weaknesses.item4': 'Adaptation process',
    'swot.opportunities.item1': 'AFAD SHM directive',
    'swot.opportunities.item2': 'Smart City projects',
    'swot.opportunities.item3': 'Public-private partnerships',
    'swot.opportunities.item4': 'Adaptation to other disasters',
    'swot.threats.item1': 'Data localization laws',
    'swot.threats.item2': 'Crypto regulations',
    'swot.threats.item3': 'Competition with traditional solutions',
    'swot.threats.item4': 'Slow corporate adoption',
    // Old flat SWOT keys (can be reviewed or removed later if not used elsewhere)
    'strengths': 'Strengths',
    'weaknesses': 'Weaknesses',
    'opportunities': 'Opportunities',
    'threats': 'Threats',
    'decentralized.communication': 'Decentralized, resilient communication',
    'realtime.damage.detection': 'Real-time damage detection',
    'transparent.data.management': 'Transparent data management',
    'automatic.coordination': 'Automatic coordination',
    'lorawan.limitations': 'LoRaWAN data limitations',
    'initial.setup.cost': 'Initial setup cost',
    'network.density.dependency': 'Network density dependency',
    'adaptation.process': 'Adaptation process',
    'afad.shm.directive': 'AFAD SHM directive',
    'smart.city.projects': 'Smart City projects',
    'public.private.partnerships': 'Public-private partnerships',
    'disaster.adaptation': 'Adaptation to other disasters',
    'data.localization.laws': 'Data localization laws',
    'crypto.regulations': 'Crypto regulations',
    'traditional.solution.competition': 'Competition with traditional solutions',
    'slow.corporate.adoption': 'Slow corporate adoption',

    // Roadmap
    'ruptura.roadmap': 'RUPTURA Roadmap',
    'phase.1': 'Phase 1',
    'phase.2': 'Phase 2',
    'phase.3': 'Phase 3',
    'phase.4': 'Phase 4',
    'proof.of.concept': 'Proof of Concept',
    'proof.of.concept.desc': 'LoRaWAN compatible sensor prototype',
    'pilot.projects': 'Pilot Projects',
    'pilot.projects.desc': 'Test applications in selected regions',
    'scaling': 'Scaling',
    'scaling.desc': 'Turkey-wide expansion',
    'international': 'International',
    'international.desc': 'Global market expansion',

    // GitHub Link
    'github.repo': 'GitHub Repo',
    'code.and.docs': 'Code & Docs',

    // Footer
    'footer.powered.by': 'Powered by',
    'footer.copyright': '© 2025 RUPTURA - Uninterrupted Communication and Rapid Damage Detection in Disasters. All rights reserved.',
    'quick.links': 'Quick Links',
    'technology': 'Technology',
    'map': 'Map',
    'market.analysis': 'Market Analysis',
    'swot': 'SWOT',
    'roadmap': 'Roadmap',
    'contact': 'Contact',
    'footer.description': 'Next-generation disaster management revolutionary technology solutions. Uninterrupted communication and rapid damage detection in disasters with Helium, IoT and Blockchain technologies.',
    'footer.countries': 'Countries',
    'footer.monitoring': 'Monitoring',
    'footer.response': 'Response',
    'footer.link.technology': 'Technology',
    'footer.link.map': 'Map',
    'footer.link.market.analysis': 'Market Analysis',
    'footer.link.swot': 'SWOT',
    'footer.link.roadmap': 'Roadmap',
    'footer.location': 'Istanbul, Turkey',
    // Old flat footer keys (can be reviewed or removed later if not used elsewhere)
    'countries': 'Countries',
    'monitoring': 'Monitoring',
    'response': 'Response',
    'powered.by': 'Powered by',
    'copyright': '© 2025 RUPTURA - Uninterrupted Communication and Rapid Damage Detection in Disasters. All rights reserved.',
    'helium': 'Helium',
    'iot': 'IoT',
    'blockchain.tech': 'Blockchain',
    'next.generation': 'Next-generation disaster management revolutionary technology solutions. Uninterrupted communication and rapid damage detection in disasters with Helium, IoT and Blockchain technologies.',
    'system.active.footer': 'System Active',

    // Additional Map and UI translations
    'loading.map': 'Loading map...',
    'live.data.indicator': 'LIVE DATA',
    'zoom.level': 'Zoom',
    'street.detail': 'Street Detail',
    'building.detail': 'Building Detail',
    'map.legend': 'Damage Levels',
    'high.damage.legend': 'High Damage (>15%)',
    'medium.damage.legend': 'Medium Damage (8-15%)',
    'low.damage.legend': 'Low Damage (3-8%)',
    'minimal.damage.legend': 'Minimal Damage (<3%)',
    'detailed.map.discovery': 'Detailed Map Discovery',
    'zoom.to.istanbul': 'Zoom to Istanbul',
    'street.level.details.tip': 'Street level details',
    'info.for.each.building': 'Information for each building',
    'explore.immediately': 'Explore Immediately',
    'emergency.teams.loading': 'Emergency teams map loading...',
    'research.phase.feature': 'Feature in Research Phase',
    'live.tracking.system': 'Live Tracking System',
    'all.emergency.teams': 'Live tracking of all emergency teams',
    'automatic.routing': 'Automatic routing with sensor data',
    'research.ongoing': 'This feature is currently in the research phase, and technology and feasibility studies are ongoing.',
    'technology.study': 'Technology Study',
    'feasibility.study': 'Feasibility Study',
    'application.planning': 'Application Planning',
    'current.situation.crisis': 'Current Situation: Communication Crisis During Disasters',
    'traditional.infrastructure.collapse': 'When traditional infrastructures collapse, life-saving information is lost',
    'potential.infrastructure.loss.turkey': 'Potential infrastructure loss observed in major disasters in Turkey',
    'physical.damage.overloading': 'Physical damage and overloading',
    'manual.processes.security.risks': 'Manual processes and security risks',
    'inefficiency.in.aid.operations': 'Inefficiency in aid operations',
    'revolutionary.disaster.management': 'Revolutionary disaster management with IoT, Helium and Blockchain',
    'instant.damage.detection.visualization': 'Instant damage detection and visualization with RUPTURA system',
    'district.street.level.detail': 'You can view detailed damage information at district and street level by zooming in on Istanbul',
    'real.street.names.building.numbers': 'Discover real street names, building numbers and detailed damage simulations by zooming in to Istanbul city. You can view floor count, resident count and damage status information for each building.',
    'real.time.response.status': 'Real-time response status and mission information of all search and rescue teams',
    'transmission.decentralized.network': 'Transmission of sensor data over the decentralized Helium network and network performance metrics',
    'processing.blockchain.damage.analysis': 'Processing sensor data on blockchain, damage analysis and automatic response triggers',
    'automatically.triggering.emergency.aid': 'Automatically triggering emergency aid processes according to predefined rules',
    'building.type': 'Building Type',
    'collapse.flag': 'Collapse Flag',
    'notification': 'Notification',
    'residential': 'Residential',
    'commercial': 'Commercial',
    'school': 'School',
    'hospital': 'Hospital',
    'shopping.center': 'Shopping Center',
    'under.research.caps': 'UNDER RESEARCH',
    'research.phase.caps': 'RESEARCH PHASE',
    'technology.review.caps': 'TECHNOLOGY REVIEW',
    'implementation.planning.caps': 'IMPLEMENTATION PLANNING',

    // Hardcoded Turkish texts in page
    'marmara.sea': 'Marmara Sea',
    'istanbul.offshore': 'Istanbul Offshore',
    'northwestern.turkey': 'Northwestern Turkey',
    'sea.of.marmara': 'Sea of Marmara',
    'fatih': 'Fatih',
    'beyoglu': 'Beyoglu',
    'besiktas': 'Besiktas',
    'kadikoy': 'Kadikoy',
    'uskudar': 'Uskudar',
    'sisli': 'Sisli',
    'bakirkoy': 'Bakirkoy',
    'zeytinburnu': 'Zeytinburnu',
    'eminonu': 'Eminonu',
    'beylikduzu': 'Beylikduzu',
    'office': 'Office',
    'building.damage.title': 'Building Damage',
    'damaged.building': 'Damaged Building',
    'building.damage.short': 'Building Damage',
    'emergency.teams.research': '🔬\nFeature Under Research',
    'emergency.research.title': '🚨 Emergency Teams Live Tracking System',
    'realtime.location.title': '📍 Real-time Location',
    'realtime.location.full.desc': 'Live tracking of all emergency teams',
    'team.coordination.title': '🚔 Team Coordination',
    'team.coordination.full.desc': 'Police, Fire Department, AFAD, AKUT integration',
    'mission.management.title': '📊 Mission Management',
    'mission.management.full.desc': 'Automatic task assignment and tracking',
    'ruptura.integration.title': '⚡ RUPTURA Integration',
    'ruptura.integration.full.desc': 'Automatic routing with sensor data',
    'police.coordination.title': '🚔\nPolice Coordination',
    'police.coordination.full.desc': 'Real-time locations and mission status of police teams',
    'fire.afad.title': '🚒\nFire Department & AFAD',
    'fire.afad.full.desc': 'Live tracking of fire, rescue and coordination teams',
    'health.akut.title': '🚑\nHealth & AKUT',
    'health.akut.full.desc': 'Automatic routing of ambulance and search rescue teams',
    'zoom.istanbul.detail.title': '🔍 Detailed Map Discovery',
    'zoom.istanbul.detail.desc': 'Zoom in to Istanbul and see real street-level damage simulations! Detailed information is available for each building.',
    'detailed.experience.title': '🎯 Detailed Map Experience',
    'detailed.experience.desc': 'By zooming in to Istanbul city, discover real street names, building numbers and detailed damage simulations. You can view floor count, resident count and damage status information for each building.',
    'next.generation.disaster.management': 'Next-generation disaster management revolutionary technology solutions. Uninterrupted communication and rapid damage detection in disasters with Helium, IoT and Blockchain technologies.',
    'istanbul.turkey': 'Istanbul, Turkey',
    'copyright.text': '© 2025 RUPTURA - Uninterrupted Communication and Rapid Damage Detection in Disasters. All rights reserved. | ruptura.online',
    'decentralized.resilient.communication': 'Decentralized, resilient communication',
    'lorawan.data.limitations': 'LoRaWAN data limitations',
    'initial.setup.cost.full': 'Initial setup cost',
    'network.density.dependency.full': 'Network density dependency',
    'adaptation.process.full': 'Adaptation process',
    'afad.shm.directive.full': 'AFAD SHM directive',
    'smart.city.projects.full': 'Smart City projects',
    'public.private.partnerships.full': 'Public-private partnerships',
    'other.disaster.adaptation': 'Adaptation to other disasters',
    'data.localization.laws.full': 'Data localization laws',
    'crypto.regulations.full': 'Crypto regulations',
    'traditional.solution.competition.full': 'Competition with traditional solutions',
    'slow.corporate.adoption.full': 'Slow corporate adoption',

    // Zoom indicators
    'street.detail.indicator': 'Street Detail',
    'building.detail.indicator': 'Building Detail',

    // Acknowledgment messages
    'project.acknowledgment.banner': 'This project is being developed by Yusuf Örnek, a student of Istanbul University MIS department, for the Blockchain Programming course by Assoc. Prof. Dr. Emre Akadal.',
    'project.acknowledgment.footer.title': 'Project Information & Acknowledgments',
    'project.acknowledgment.footer.desc1': 'This project is being developed by Yusuf Örnek, a student of the Management Information Systems department at Istanbul University, within the scope of the Blockchain Programming course taught by Assoc. Prof. Dr. Emre Akadal.',
    'project.acknowledgment.footer.desc2': 'RUPTURA is a project exploring the use of blockchain technology in earthquake management. The approach of our professor, Assoc. Prof. Dr. Emre Akadal, in demonstrating how blockchain technology can be integrated into daily life, led to the emergence of this project.',
    'project.acknowledgment.footer.desc3': 'I would like to express my gratitude to Istanbul University, Department of Management Information Systems, and Assoc. Prof. Dr. Emre Akadal for their support during this project development process.',
    'project.developer': 'Developer: Yusuf Örnek (Student, Management Information Systems)',
    'project.status': '* This project is currently in the development phase.',
    'project.course': 'Blockchain Programming Course (Instructor: Assoc. Prof. Dr. Emre Akadal)',
    'project.department': 'Management Information Systems Department',
    'project.university': 'Istanbul University'
  },
  tr: {
    // Header
    'system.active': 'SİSTEM AKTİF',
    'system.title': 'Afetlerde Kesintisiz İletişim ve Hızlı Hasar Tespiti',
    'system.subtitle': 'Helium, IoT ve Blokzincir Teknolojileri ile Gelecek Nesil Afet Yönetimi',
    'latest.earthquake.data': 'Son Deprem Verileri',
    'active.hotspots': 'Aktif Hotspot',
    'connected.sensors': 'Bağlı Sensör',
    'todays.alerts': 'Bugünkü Uyarı',
    'response.time': 'Yanıt Süresi',

    // Modal
    'welcome.modal.platform.type': 'Afet Yönetim Platformu',
    'welcome.modal.title': 'RUPTURA\'ya Hoş Geldiniz',
    'welcome.modal.demo.purpose.title': 'Tanıtım Amacı',
    'welcome.modal.demo.purpose.desc': 'Bu platform, RUPTURA sisteminin yeteneklerini simüle edilmiş veri ve senaryolarla sergilemektedir. Tüm veriler yalnızca tanıtım amaçlıdır.',
    'welcome.modal.platform.aim.title': 'Platformun Hedefi',
    'welcome.modal.platform.aim.desc': 'RUPTURA\'nın afet iletişimini ve hasar tespitini nasıl devrimleştirebileceğine dair interaktif bir deneyim sunmak.',
    'welcome.modal.content.info.title': 'İçerik Bilgileri',
    'welcome.modal.content.info.item1': 'Simüle edilmiş sensör verileri ve hasar raporları.',
    'welcome.modal.content.info.item2': 'Gerçek zamanlı görselleştirmeler ve animasyonlar.',
    'welcome.modal.content.info.item3': 'Teknolojik özellikler için kavram kanıtı.',
    'welcome.modal.usage.terms.title': 'Kullanım Koşulları',
    'welcome.modal.usage.terms.desc': 'Bu platform yalnızca bilgilendirme ve eğitim amaçlıdır. Gerçek acil durumlarda kullanılmamalıdır.',
    'welcome.modal.button.text': 'Anladım & Devam Et',
    'welcome.modal.first.visit.message': 'Bu mesaj yalnızca ilk ziyaretinizde gösterilir.',
    // Old Modal Keys (can be reviewed or removed later if not used elsewhere)
    'important.notice': 'Önemli Bilgilendirme',
    'demo.simulation.platform': 'Demo ve Simülasyon Amaçlı Platform',
    'demo.simulation.desc': 'Bu site üzerindeki tüm veriler simülasyon ve demo amaçlıdır. Gerçek deprem verileri, hasar bilgileri veya acil durum verileri değildir.',
    'platform.purpose': 'Platform Amacı',
    'platform.purpose.desc': 'RUPTURA sisteminin teknolojik yeteneklerini ve nasıl çalıştığını göstermek için tasarlanmış interaktif bir demonstrasyon platformudur.',
    'content.about': 'İçerik Hakkında',
    'content.item1': 'Dummy sensör verileri ve hasar simülasyonları',
    'content.item2': 'Gerçek zamanlı animasyonlar ve görselleştirmeler',
    'content.item3': 'Teknoloji demonstrasyonu ve kavram kanıtı',
    'usage.conditions': 'Kullanım Koşulları',
    'usage.conditions.desc': 'Platform sadece bilgilendirme, eğitim ve teknoloji tanıtım amaçlıdır. Gerçek acil durumlarda kullanılmamalıdır.',
    'understood.enter': 'Anladım, Platforma Giriş Yap',
    'first.visit.message': 'Bu mesaj sadece ilk ziyaretinizde gösterilir', // Kept for potential other uses, new key is welcome.modal.first.visit.message

    // Crisis Section
    'current.situation': 'Mevcut Durum: Afet Anında İletişim Krizi',
    'current.situation.desc': 'Geleneksel altyapılar çöktüğünde, hayat kurtarıcı bilgiler kaybolur',
    'communication.outage': 'İletişim Kesintisi',
    'potential.infrastructure.loss': "Türkiye'deki büyük afetlerde gözlemlenen potansiyel altyapı kaybı",
    'gsm.outages': 'GSM ve Sabit Hat Kesintileri',
    'physical.damage.overload': 'Fiziksel hasar ve aşırı yüklenme',
    'delayed.damage.detection': 'Gecikmeli Hasar Tespiti',
    'manual.processes.risks': 'Manual süreçler ve güvenlik riskleri',
    'coordination.deficiency': 'Koordinasyon Eksikliği',
    'inefficiency.aid.operations': 'Yardım operasyonlarında verimsizlik',

    // Solution
    'ruptura.solution': 'RUPTURA Çözümü: Merkezi Olmayan Ağ',
    'ruptura.solution.desc': 'IoT, Helium ve Blokzincir ile devrimsel afet yönetimi',
    'iot.sensors': 'IoT Sensörleri',
    'iot.sensors.desc': 'Gerçek zamanlı hasar tespiti',
    'helium.network': 'Helium Ağı',
    'helium.network.desc': 'Merkezi olmayan iletişim',
    'blockchain': 'Blokzincir',
    'blockchain.desc': 'Değişmez veri kaydı',
    'gis.aid': 'CBS & Yardım',
    'gis.aid.desc': 'Otomatik koordinasyon',

    // Map Section
    'turkey.realtime.damage.map': 'Türkiye Gerçek Zamanlı Hasar Haritası',
    'turkey.map.desc': 'RUPTURA sistemi ile anlık hasar tespiti ve görselleştirme',
    'turkey.map.detail': "İstanbul'da yakınlaştırarak ilçe ve sokak seviyesinde detaylı hasar bilgilerini görüntüleyebilirsiniz",
    'map.controls': 'Harita Kontrolleri',
    'zoom.in': 'Yakınlaştır',
    'zoom.out': 'Uzaklaştır',
    'istanbul.detail': 'İstanbul Detay',
    'all.damages': 'Tüm Hasarlar',
    'collapsed.buildings': 'Yıkık Binalar',
    'severely.damaged': 'Ağır Hasarlı',
    'infrastructure.damages': 'Altyapı Hasarları',
    'live.data': 'Canlı Veri',
    'map.loading': 'Harita yükleniyor...',
    'detailed.map.exploration': 'Detaylı Harita Keşfi',
    'zoom.istanbul.desc': "İstanbul'a yakınlaştırın ve sokak seviyesinde gerçek hasar simülasyonlarını görün! Her bina için detaylı bilgiler mevcut.",
    'go.to.istanbul': "İstanbul'a Git",
    'damage.levels': 'Hasar Seviyeleri',
    'high.damage': 'Yüksek Hasar (>15%)',
    'medium.damage': 'Orta Hasar (8-15%)',
    'low.damage': 'Az Hasar (3-8%)',
    'minimal.damage': 'Düşük Hasar (<3%)',
    'tip': 'İpucu',
    'zoom.istanbul.tip': "İstanbul'a zoom yapın",
    'street.level.details': 'Sokak seviyesi detaylar',
    'info.each.building': 'Her bina için bilgi',
    'detailed.map.experience': 'Detaylı Harita Deneyimi',
    'zoom.istanbul.experience': "İstanbul şehrine yakınlaştırarak gerçek sokak isimlerini, bina numaralarnı ve detaylı hasar simülasyonlarını keşfedin. Her bina için kat sayısı, sakin sayısı ve hasar durumu bilgilerini görüntüleyebilirsiniz.",
    'building.details': '150+ Bina Detayı',
    'district.coverage': '10 İlçe Kapsamı',
    'real.addresses': 'Gerçek Adresler',
    'explore.now': 'Hemen Keşfet',

    // Emergency Teams
    'emergency.teams.live.tracking': 'Acil Durum Ekipleri Canlı Takip',
    'emergency.teams.desc': 'Emniyet, İtfaiye, AFAD, AKUT ve Sağlık ekiplerinin anlık konumları',
    'emergency.teams.detail': 'Tüm arama kurtarma ekiplerinin gerçek zamanlı müdahale durumları ve görev bilgileri',
    'under.research': 'ARAŞTIRMA AŞAMASINDA',
    'feature.under.research': 'Araştırma Aşamasında Olan Özellik',
    'emergency.teams.system': 'Acil Durum Ekipleri Canlı Takip Sistemi',
    'realtime.location': 'Gerçek Zamanlı Konum',
    'realtime.location.desc': 'Tüm acil durum ekiplerinin anlık takibi',
    'team.coordination': 'Ekip Koordinasyonu',
    'team.coordination.desc': 'Emniyet, İtfaiye, AFAD, AKUT entegrasyonu',
    'mission.management': 'Görev Yönetimi',
    'mission.management.desc': 'Otomatik görev atama ve takip',
    'ruptura.integration': 'RUPTURA Entegrasyonu',
    'ruptura.integration.desc': 'Sensör verileri ile otomatik yönlendirme',
    'research.phase.desc': 'Bu özellik şu anda araştırma aşamasında olup, teknoloji ve uygulanabilirlik çalışmaları devam etmektedir.', // Value for feature.under.research.desc
    'feature.under.research.desc': 'Bu özellik şu anda araştırma aşamasında olup, teknoloji ve uygulanabilirlik çalışmaları devam etmektedir.',
    'research.phase': 'Araştırma Aşamasında',
    'technology.review': 'Teknoloji İncelemesi',
    'implementation.planning': 'Uygulama Planlaması',
    'under.research.status': 'Araştırma Aşamasında',
    'feature.under.research.title': 'Araştırma Aşamasında Olan Özellik', // Value from 'feature.under.research'
    'emergency.teams.live.tracking.system': 'Acil Durum Ekipleri Canlı Takip Sistemi', // Value from 'emergency.teams.system'
    'police.coordination': 'Emniyet Koordinasyonu',
    'police.coordination.desc': 'Polis ekiplerinin gerçek zamanlı konumları ve görev durumları',
    'firedept.afad': 'İtfaiye & AFAD',
    'firedept.afad.desc': 'Yangın, kurtarma ve koordinasyon ekiplerinin canlı takibi',
    'health.akut': 'Sağlık & AKUT',
    'health.akut.desc': 'Ambulans ve arama kurtarma ekiplerinin otomatik yönlendirmesi',

    // Statistics
    'total.collapsed.buildings': 'Toplam Yıkık Bina',
    'turkey.wide': 'Türkiye Geneli',
    'severely.damaged.buildings': 'Ağır Hasarlı',
    'urgent.intervention.required': 'Acil Müdahale Gerekli',
    'affected.cities': 'Etkilenen Şehir',
    'active.monitoring': 'Aktif İzleme',
    'active.sensors': 'Aktif Sensör',
    'data.collection': 'Veri Toplama',

    // Map Data
    'population': 'Nüfus',
    'total.buildings': 'Toplam Bina',
    'damaged.buildings': 'Hasarlı Bina',
    'damage.rate': 'Hasar Oranı',
    'show.details': 'Detayları Göster',
    'address': 'Adres',
    'district': 'İlçe',
    'status': 'Durum',
    'floor.count': 'Kat Sayısı',
    'residents': 'Sakin',
    'time': 'Saat',
    'building.damage': 'Bina Hasarı',
    'collapsed': 'Yıkık',
    'severe': 'Ağır Hasarlı',
    'moderate': 'Orta Hasarlı',
    'light': 'Az Hasarlı',
    'intact': 'Hasarsız',

    // City Details
    'detailed.damage.report': 'Detaylı Hasar Raporu',
    'building.statistics': 'Bina İstatistikleri',
    'recent.events': 'Son Olaylar',
    'damage.distribution': 'Hasar Dağılımı',

    // Market Potential
    'market.potential.growth': 'Pazar Potansiyeli ve Büyüme',
    'helium.hotspots': 'Aktif Helium Hotspot',
    'country.coverage': 'Ülke Kapsamı',
    'cities.towns': 'Şehir/Kasaba',

    // Technology Stack
    'technology.stack': 'Teknoloji Yığını',
    'smart.sensor.technologies': 'Akıllı Sensör Teknolojileri',
    'accelerometers': 'İvmeölçerler (MEMS)',
    'vibration.detection': 'Sarsıntı ve titreşim',
    'omron.d7s': 'Omron D7S',
    'earthquake.intensity': 'Deprem şiddeti tespiti',
    'strain.gauges': 'Gerinim Ölçerler',
    'structural.deformation': 'Yapısal deformasyon',
    'gps.sensors': 'GPS Sensörleri',
    'precise.location': 'Hassas konum takibi',
    'edge.computing.ai': 'Uç Bilişim ve AI',
    'realtime.processing': 'Gerçek Zamanlı İşleme',
    'realtime.processing.desc': 'Ham sismik verilerin yerel filtrelenmesi ve LoRaWAN uyumlu özet metriklerin üretilmesi',
    'machine.learning': 'Makine Öğrenmesi',
    'machine.learning.desc': 'Hasar tahmin algoritmaları ve anomali tespiti için gelişmiş AI modelleri',

    // Live System Demo
    'ruptura.live.demo': 'RUPTURA Canlı Sistem Demonstrasyonu',
    'ruptura.demo.desc': 'Omron Sensörü Verilerine Göre Akıllı Kontrat Aktivasyonu ve Anlık Uyarı Sistemi',
    'ruptura.demo.detail': 'Gerçek zamanlı sensör verileri, akıllı kontrat tetiklemeleri ve animasyonlu uyarı görselleştirmeleri',

    // System Components
    'system.components.demo': 'Sistem Bileşenleri - Canlı Demonstrasyon',
    'system.components.desc': 'RUPTURA sisteminin tüm bileşenlerinin gerçek zamanlı çalışma demonstrasyonu',
    'omron.sensor.network': 'Omron D7S Sensör Ağı Simülatörü',
    'omron.sensor.desc': 'İstanbul genelinde dağıtılmış Omron D7S sensörlerinin gerçek zamanlı veri üretimi ve hasar analizi',
    'helium.lorawan.monitor': 'Helium LoRaWAN Ağı Monitörü',
    'helium.monitor.desc': 'Merkezi olmayan Helium ağı üzerinden sensör verilerinin iletimi ve ağ performans metrikleri',
    'smart.contract.processor': 'Akıllı Kontrat İşleyici',
    'smart.contract.desc': 'Sensör verilerinin blokzincir üzerinde işlenmesi, hasar analizi ve otomatik müdahale tetiklemeleri',

    // Blockchain Benefits
    'blockchain.trust.transparency': 'Blokzincir ile Güven ve Şeffaflık',
    'immutable.record': 'Değişmez Kayıt',
    'immutable.record.desc': 'Veriler sonradan değiştirilemez',
    'full.transparency': 'Tam Şeffaflık',
    'full.transparency.desc': 'Tüm işlemler görülebilir',
    'reliability': 'Güvenilirlik',
    'reliability.desc': 'Manipülasyona kapalı sistem',
    'automatic.aid.smart.contracts': 'Akıllı Sözleşmelerle Otomatik Yardım',
    'automatic.aid.desc': 'Önceden tanımlanmış kurallara göre acil yardım süreçlerini otomatik tetikleme',
    'example.scenario': 'Örnek Senaryo:',
    'jma.scenario': '"JMA 5+ şiddetinde sarsıntı + çökme bayrağı → Otomatik arama-kurtarma ekibi bildirimi"',

    // SWOT Analysis
    'turkey.market.swot': 'Türkiye Pazarı: SWOT Analizi',
    'swot.strengths.title': 'Güçlü Yönler',
    'swot.weaknesses.title': 'Zayıf Yönler',
    'swot.opportunities.title': 'Fırsatlar',
    'swot.threats.title': 'Tehditler',
    'swot.strengths.item1': 'Merkezi olmayan, dayanıklı iletişim',
    'swot.strengths.item2': 'Gerçek zamanlı hasar tespiti',
    'swot.strengths.item3': 'Şeffaf veri yönetimi',
    'swot.strengths.item4': 'Otomatik koordinasyon',
    'swot.weaknesses.item1': 'LoRaWAN veri kısıtlamaları',
    'swot.weaknesses.item2': 'İlk kurulum maliyeti',
    'swot.weaknesses.item3': 'Ağ yoğunluğuna bağımlılık',
    'swot.weaknesses.item4': 'Adaptasyon süreci',
    'swot.opportunities.item1': 'AFAD SHM direktifi',
    'swot.opportunities.item2': 'Akıllı Şehir projeleri',
    'swot.opportunities.item3': 'Kamu-özel işbirlikleri',
    'swot.opportunities.item4': 'Diğer afetlere uyarlama',
    'swot.threats.item1': 'Veri yerelleştirme yasaları',
    'swot.threats.item2': 'Kripto düzenlemeleri',
    'swot.threats.item3': 'Geleneksel çözümlerle rekabet',
    'swot.threats.item4': 'Yavaş kurumsal kabul',
    // Old flat SWOT keys (can be reviewed or removed later if not used elsewhere)
    'strengths': 'Güçlü Yönler',
    'weaknesses': 'Zayıf Yönler',
    'opportunities': 'Fırsatlar',
    'threats': 'Tehditler',
    'decentralized.communication': 'Merkezi olmayan, dayanıklı iletişim',
    'realtime.damage.detection': 'Gerçek zamanlı hasar tespiti',
    'transparent.data.management': 'Şeffaf veri yönetimi',
    'automatic.coordination': 'Otomatik koordinasyon',
    'lorawan.limitations': 'LoRaWAN veri kısıtlamaları',
    'initial.setup.cost': 'İlk kurulum maliyeti',
    'network.density.dependency': 'Ağ yoğunluğuna bağımlılık',
    'adaptation.process': 'Adaptasyon süreci',
    'afad.shm.directive': 'AFAD SHM direktifi',
    'smart.city.projects': 'Akıllı Şehir projeleri',
    'public.private.partnerships': 'Kamu-özel işbirlikleri',
    'disaster.adaptation': 'Diğer afetlere uyarlama',
    'data.localization.laws': 'Veri yerelleştirme yasaları',
    'crypto.regulations': 'Kripto düzenlemeleri',
    'traditional.solution.competition': 'Geleneksel çözümlerle rekabet',
    'slow.corporate.adoption': 'Yavaş kurumsal kabul',

    // Roadmap
    'ruptura.roadmap': 'RUPTURA Yol Haritası',
    'phase.1': 'Faz 1',
    'phase.2': 'Faz 2',
    'phase.3': 'Faz 3',
    'phase.4': 'Faz 4',
    'proof.of.concept': 'Konsept Kanıtı',
    'proof.of.concept.desc': 'LoRaWAN uyumlu sensör prototipi',
    'pilot.projects': 'Pilot Projeler',
    'pilot.projects.desc': 'Seçili bölgelerde test uygulamaları',
    'scaling': 'Ölçeklendirme',
    'scaling.desc': 'Türkiye geneli yaygınlaştırma',
    'international': 'Uluslararası',
    'international.desc': 'Küresel pazar genişlemesi',

    // GitHub Link
    'github.repo': 'GitHub Repo',
    'code.and.docs': 'Kod & Dokümanlar',

    // Footer
    'footer.powered.by': 'Powered by',
    'footer.copyright': '© 2025 RUPTURA - Afetlerde Kesintisiz İletişim ve Hızlı Hasar Tespiti. Tüm hakları saklıdır.',
    'quick.links': 'Hızlı Bağlantılar',
    'technology': 'Teknoloji',
    'map': 'Harita',
    'market.analysis': 'Pazar Analizi',
    'swot': 'SWOT',
    'roadmap': 'Yol Haritası',
    'contact': 'İletişim',
    'footer.description': 'Gelecek nesil afet yönetimi için devrimsel teknoloji çözümleri. Helium, IoT ve Blokzincir teknolojileri ile afetlerde kesintisiz iletişim ve hızlı hasar tespiti.',
    'footer.countries': 'Ülke',
    'footer.monitoring': 'İzleme',
    'footer.response': 'Yanıt',
    'footer.link.technology': 'Teknoloji',
    'footer.link.map': 'Harita',
    'footer.link.market.analysis': 'Pazar Analizi',
    'footer.link.swot': 'SWOT',
    'footer.link.roadmap': 'Yol Haritası',
    'footer.location': 'İstanbul, Türkiye',
    // Old flat footer keys (can be reviewed or removed later if not used elsewhere)
    'countries': 'Ülke',
    'monitoring': 'İzleme',
    'response': 'Yanıt',
    'powered.by': 'Powered by',
    'copyright': '© 2025 RUPTURA - Afetlerde Kesintisiz İletişim ve Hızlı Hasar Tespiti. Tüm hakları saklıdır.',
    'helium': 'Helium',
    'iot': 'IoT',
    'blockchain.tech': 'Blockchain',
    'next.generation': 'Gelecek nesil afet yönetimi için devrimsel teknoloji çözümleri. Helium, IoT ve Blokzincir teknolojileri ile afetlerde kesintisiz iletişim ve hızlı hasar tespiti.',
    'system.active.footer': 'Sistem Aktif',

    // Additional Map and UI translations
    'loading.map': 'Harita yükleniyor...',
    'live.data.indicator': 'CANLI VERİ',
    'zoom.level': 'Zoom',
    'street.detail': 'Sokak Detayı',
    'building.detail': 'Bina Detayı',
    'map.legend': 'Hasar Seviyeleri',
    'high.damage.legend': 'Yüksek Hasar (>15%)',
    'medium.damage.legend': 'Orta Hasar (8-15%)',
    'low.damage.legend': 'Az Hasar (3-8%)',
    'minimal.damage.legend': 'Düşük Hasar (<3%)',
    'detailed.map.discovery': 'Detaylı Harita Keşfi',
    'zoom.to.istanbul': 'İstanbul\'a zoom yapın',
    'street.level.details.tip': 'Sokak seviyesi detaylar',
    'info.for.each.building': 'Her bina için bilgi',
    'explore.immediately': 'Hemen Keşfet',
    'emergency.teams.loading': 'Acil durum ekipleri haritası yükleniyor...',
    'research.phase.feature': 'Araştırma Aşamasında Olan Özellik',
    'live.tracking.system': 'Canlı Takip Sistemi',
    'all.emergency.teams': 'Tüm acil durum ekiplerinin anlık takibi',
    'automatic.routing': 'Sensör verileri ile otomatik yönlendirme',
    'research.ongoing': 'Bu özellik şu anda araştırma aşamasında olup, teknoloji ve uygulanabilirlik çalışmaları devam etmektedir.',
    'technology.study': 'Teknoloji İncelemesi',
    'feasibility.study': 'Uygulanabilirlik Çalışması',
    'application.planning': 'Uygulama Planlaması',
    'current.situation.crisis': 'Mevcut Durum: Afet Anında İletişim Krizi',
    'traditional.infrastructure.collapse': 'Geleneksel altyapılar çöktüğünde, hayat kurtarıcı bilgiler kaybolur',
    'potential.infrastructure.loss.turkey': 'Türkiye\'deki büyük afetlerde gözlemlenen potansiyel altyapı kaybı',
    'physical.damage.overloading': 'Fiziksel hasar ve aşırı yüklenme',
    'manual.processes.security.risks': 'Manual süreçler ve güvenlik riskleri',
    'inefficiency.in.aid.operations': 'Yardım operasyonlarında verimsizlik',
    'revolutionary.disaster.management': 'IoT, Helium ve Blokzincir ile devrimsel afet yönetimi',
    'instant.damage.detection.visualization': 'RUPTURA sistemi ile anlık hasar tespiti ve görselleştirme',
    'district.street.level.detail': 'İstanbul\'da yakınlaştırarak ilçe ve sokak seviyesinde detaylı hasar bilgilerini görüntüleyebilirsiniz',
    'real.street.names.building.numbers': 'İstanbul şehrine yakınlaştırarak gerçek sokak isimlerini, bina numaralarını ve detaylı hasar simülasyonlarını keşfedin. Her bina için kat sayısı, sakin sayısı ve hasar durumu bilgilerini görüntüleyebilirsiniz.',
    'real.time.response.status': 'Tüm arama kurtarma ekiplerinin gerçek zamanlı müdahale durumları ve görev bilgileri',
    'transmission.decentralized.network': 'Merkezi olmayan Helium ağı üzerinden sensör verilerinin iletimi ve ağ performans metrikleri',
    'processing.blockchain.damage.analysis': 'Sensör verilerinin blokzincir üzerinde işlenmesi, hasar analizi ve otomatik müdahale tetiklemeleri',
    'automatically.triggering.emergency.aid': 'Önceden tanımlanmış kurallara göre acil yardım süreçlerini otomatik tetikleme',
    'building.type': 'Bina Türü',
    'collapse.flag': 'Çökme Bayrağı',
    'notification': 'Bildirim',
    'residential': 'Konut',
    'commercial': 'Ticari',
    'school': 'Okul',
    'hospital': 'Hastane',
    'shopping.center': 'Alışveriş Merkezi',
    'under.research.caps': 'ARAŞTIRMA AŞAMASINDA',
    'research.phase.caps': 'ARAŞTIRMA AŞAMASINDA',
    'technology.review.caps': 'TEKNOLOJİ İNCELEMESİ',
    'implementation.planning.caps': 'UYGULAMA PLANLAMASI',

    // Hardcoded Turkish texts in page - TR versions
    'marmara.sea': 'Marmara Denizi',
    'istanbul.offshore': 'İstanbul Açıkları',
    'northwestern.turkey': 'Kuzeybatı Türkiye',
    'sea.of.marmara': 'Marmara Denizi',
    'fatih': 'Fatih',
    'beyoglu': 'Beyoğlu',
    'besiktas': 'Beşiktaş',
    'kadikoy': 'Kadıköy',
    'uskudar': 'Üsküdar',
    'sisli': 'Şişli',
    'bakirkoy': 'Bakırköy',
    'zeytinburnu': 'Zeytinburnu',
    'eminonu': 'Eminönü',
    'beylikduzu': 'Beylikdüzü',
    'office': 'Ofis',
    'building.damage.title': 'Bina Hasarı',
    'damaged.building': 'Hasarlı Bina',
    'building.damage.short': 'Bina Hasarı',
    'emergency.teams.research': '🔬\nAraştırma Aşamasında Olan Özellik',
    'emergency.research.title': '🚨 Acil Durum Ekipleri Canlı Takip Sistemi',
    'realtime.location.title': '📍 Gerçek Zamanlı Konum',
    'realtime.location.full.desc': 'Tüm acil durum ekiplerinin anlık takibi',
    'team.coordination.title': '🚔 Ekip Koordinasyonu',
    'team.coordination.full.desc': 'Emniyet, İtfaiye, AFAD, AKUT entegrasyonu',
    'mission.management.title': '📊 Görev Yönetimi',
    'mission.management.full.desc': 'Otomatik görev atama ve takip',
    'ruptura.integration.title': '⚡ RUPTURA Entegrasyonu',
    'ruptura.integration.full.desc': 'Sensör verileri ile otomatik yönlendirme',
    'police.coordination.title': '🚔\nEmniyet Koordinasyonu',
    'police.coordination.full.desc': 'Polis ekiplerinin gerçek zamanlı konumları ve görev durumları',
    'fire.afad.title': '🚒\nİtfaiye & AFAD',
    'fire.afad.full.desc': 'Yangın, kurtarma ve koordinasyon ekiplerinin canlı takibi',
    'health.akut.title': '🚑\nSağlık & AKUT',
    'health.akut.full.desc': 'Ambulans ve arama kurtarma ekiplerinin otomatik yönlendirmesi',
    'zoom.istanbul.detail.title': '🔍 Detaylı Harita Keşfi',
    'zoom.istanbul.detail.desc': 'İstanbul\'a yakınlaştırın ve sokak seviyesinde gerçek hasar simülasyonlarını görün! Her bina için detaylı bilgiler mevcut.',
    'detailed.experience.title': '🎯 Detaylı Harita Deneyimi',
    'detailed.experience.desc': 'İstanbul şehrine yakınlaştırarak gerçek sokak isimlerini, bina numaralarını ve detaylı hasar simülasyonlarını keşfedin. Her bina için kat sayısı, sakin sayısı ve hasar durumu bilgilerini görüntüleyebilirsiniz.',
    'next.generation.disaster.management': 'Gelecek nesil afet yönetimi için devrimsel teknoloji çözümleri. Helium, IoT ve Blokzincir teknolojileri ile afetlerde kesintisiz iletişim ve hızlı hasar tespiti.',
    'istanbul.turkey': 'İstanbul, Türkiye',
    'copyright.text': '© 2025 RUPTURA - Afetlerde Kesintisiz İletişim ve Hızlı Hasar Tespiti. Tüm hakları saklıdır. | ruptura.online',
    'decentralized.resilient.communication': 'Merkezi olmayan, dayanıklı iletişim',
    'lorawan.data.limitations': 'LoRaWAN veri kısıtlamaları',
    'initial.setup.cost.full': 'İlk kurulum maliyeti',
    'network.density.dependency.full': 'Ağ yoğunluğuna bağımlılık',
    'adaptation.process.full': 'Adaptasyon süreci',
    'afad.shm.directive.full': 'AFAD SHM direktifi',
    'smart.city.projects.full': 'Akıllı Şehir projeleri',
    'public.private.partnerships.full': 'Kamu-özel işbirlikleri',
    'other.disaster.adaptation': 'Diğer afetlere uyarlama',
    'data.localization.laws.full': 'Veri yerelleştirme yasaları',
    'crypto.regulations.full': 'Kripto düzenlemeleri',
    'traditional.solution.competition.full': 'Geleneksel çözümlerle rekabet',
    'slow.corporate.adoption.full': 'Yavaş kurumsal kabul',

    // Acknowledgment messages - Turkish
    'project.acknowledgment.banner': 'Bu proje, İstanbul Üniversitesi YBS bölümü öğrencisi Yusuf Örnek tarafından, Doç. Dr. Emre Akadal\'ın verdiği Blockchain Programming dersi kapsamında geliştirilmektedir.',
    'project.acknowledgment.footer.title': 'Proje Bilgileri & Teşekkür',
    'project.acknowledgment.footer.desc1': 'Bu proje, İstanbul Üniversitesi Yönetim Bilişim Sistemleri bölümü öğrencisi Yusuf Örnek tarafından, Doç. Dr. Emre Akadal hocamın verdiği Blockchain Programming dersi kapsamında geliştirilmektedir.',
    'project.acknowledgment.footer.desc2': 'RUPTURA, deprem yönetiminde blockchain teknolojisinin kullanımını araştıran bir projedir. Hocamın blockchain teknolojisini günlük hayatla nasıl birleştirilebileceğini gösteren yaklaşımı bu projenin ortaya çıkmasını sağlamıştır.',
    'project.acknowledgment.footer.desc3': 'Bu proje geliştirme sürecindeki destekleri için İstanbul Üniversitesi YBS bölümüne ve Doç. Dr. Emre Akadal hocama teşekkürlerimi sunarım.',
    'project.developer': 'Geliştirici: Yusuf Örnek (Yönetim Bilişim Sistemleri Öğrencisi)',
    'project.status': '* Bu proje şu anda geliştirme aşamasındadır.',
    'project.course': 'Blockchain Programming Dersi (Dersi Veren: Doç. Dr. Emre Akadal)',
    'project.department': 'Yönetim Bilişim Sistemleri Bölümü',
    'project.university': 'İstanbul Üniversitesi'
  }
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en') // Default to English

  useEffect(() => {
    // Check if language preference exists in localStorage
    const savedLanguage = localStorage.getItem('ruptura-language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'tr')) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('ruptura-language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
